### ISSUE TITLE
Could SRWE have caused a problem with my graphics card or fan?

### ISSUE THREAD

**Issue by ladyche** [dtgDTGdtg/SRWE#12]
I downaloaded Simple Runtime Window Editor and changed the games files to force windowed mode. Everything was fine, the game displayed vertically and thinner but in perfect perspective.

Since doing this once, the computer has started to make strange noises, like the fan is having trouble working properly whenever I'm using graphic intense programs such as games or photo editing software. (Even on start-up the fan sounds like it's having trouble turning, it sounds clunky like it can speed up). During intensive graphics programs like games I can hear a high pitch noise and the fan hasn't sounded normal since I used the Simple Runtime Window Editor. 

Is it possible this program could have put some strain on the fan or graphics card? I don't know much about computers but mine hasn't worked normally since changing the screen resolution a few times. 

Thanks! :)

**Comment by FransBouma** [comment]
SRWE simply does the same thing as when you manually resize teh window of a game or graphically intense program. So say you have your game running in a window of 1920x1080. Then you manually resize that window with the mouse to a bigger window, say 2880x1680. The game window is now bigger and thus the game has to work harder to render the game (there are more pixels to paint as the resolution is higher). 

What you did with the resizing of the window manually results in windows sending a message to the game's window (a WM_SIZE message). The game receives this message and reacts to it: it will resize the game's resolution to match the new window's size. 

SRWE does the same thing: it simply sends a WM_SIZE message to the game's window, as if you manually resized the window with the mouse (which is now done by SRWE, but it's exactly the same for Windows and the game). So there's no magic going on or special things. 

The only problem it could cause is the same as when you pick a higher resolution in the game itself or resize the window manually: the game has to work harder, which results in more usage of the GPU / CPU and thus these get hotter and the fans therefore have to work harder to mitigate the extra heat (That's what they're there for anyway ;)). 

Over time these fans and cooling blocks on a videocard and CPU collect dust. This can lead to the fans become cluttered and not rotate that well. With the higher workload due to the higher resolution it might be the fans had to work extra hard and some dust particles have slipped into the fan's bearings, causing it to become noisy. 

What you could do is the following: (at your own risk of course)

- switch off the PC, unplug the power cord
- open the case (it's fine)
- get your vacuumcleaner, make sure it's running on the lowest power setting
- gently vacuum your CPU's fan and videocard's fan so the dust there is removed. Be gentle, it's hardware after all ;)
- close the case, plug in your power cord and switch it on. 

Highly likely it's running fine now. If you don't know whether you should do this, you can also bring your PC to a local shop and let them clean it for you. 

Good luck!

**Comment by ladyche** [comment]
Hi FransBouma,

Thanks a lot for your detailed response! I had thought it might be making my PC work harder and there is a lot of dust collected in the fans, so perhaps it simply pushed the fans too hard when I used this program. (But it's a great program actually and I'm glad I found it). 

I'll gently clean the fans (or get them cleaned and perhaps use the program sparingly and for short periods of time). 

Thanks again for your response! Have a lovely day!

Cherie :)

(I think the fact that I only have 90GB worth of free space isn't helping matters - so I'll delete some things) xD

**Comment by FransBouma** [comment]
:) Don't worry too much that the fans make noise btw, (except that the noise is annoying ;)) the CPU (motherboard) and videocard all have sensors so if they're getting too hot they'll shut off or tune down to a lower frequency (CPU) so they'll get less hot. In practice it will likely mean your game will simply crash or your computer will crash so it's not like you can burn your computer to the ground by selecting a high resolution (through SRWE or through the game's menu). 

Disk space has no influence. 90GB is plenty of space :) Cheers!
