### ISSUE TITLE
Add ability to hide processes

### ISSUE THREAD

**Issue by Keith94** [dtgDTGdtg/SRWE#6]
Hi!
In the "Select Process" window, it would be nice to remove some "clutter" which are lots of non-game processes and such.

Preferably you could add a right-click option to hide each process individually, and store it somewhere. If not, we could manually create a config file and add a list of process names to ignore. 

Also could you add support for resizing the processes window?

**Comment by FransBouma** [comment]
I think a better approach is to sort the ones which you already opened recently (SRWE knows these) at the top. Hiding things has the problem that you perhaps want to show them later at some point and you then have to unhide them again, which is also problematic because e.g. you hid 20 processes and just want to unhide one. You can already auto attach to a known process which makes it easier to start SRWE with the game you recently played. 

Resizing the processes window, good point. And remember it's last size I guess? :)

**Comment by Keith94** [comment]
>I think a better approach is to sort the ones which you already opened recently (SRWE knows these) at the top.

Sounds good! It's limited to twenty recent processes, but that seems sufficient.

Remembering last window size/position would be good too, as always.
